# Welcome to Jekyll!
title: Marc Watts
description: |
  Software developer and overkeen cyclist, based in London.
owner: Marc Watts # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: marcky.sharky@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://marckysharky.github.io" # the base hostname & protocol for your site
social:
  github: https://github.com/marckysharky
  linkedin-square: https://linkedin.com/in/marcawatts
  email: mailto:marcky.sharky@gmail.com
  hackerrank: https://www.hackerrank.com/marcky_sharky

# Build settings
markdown: kramdown
#sass:
#  style: compressed
