# Site settings
title: marckysharky
email: marcky.sharky@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ruby developer, based in London.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: marckysharky
github_username:  marckysharky

# Build settings
markdown: kramdown
